// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "key", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "ip_whitelist", Type: field.TypeJSON, Nullable: true},
		{Name: "ip_blacklist", Type: field.TypeJSON, Nullable: true},
		{Name: "quota", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "quota_used", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "rate_limit_5h", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "rate_limit_1d", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "rate_limit_7d", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "usage_5h", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "usage_1d", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "usage_7d", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "window_5h_start", Type: field.TypeTime, Nullable: true},
		{Name: "window_1d_start", Type: field.TypeTime, Nullable: true},
		{Name: "window_7d_start", Type: field.TypeTime, Nullable: true},
		{Name: "group_id", Type: field.TypeInt64, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_groups_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[22]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[23]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apikey_user_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[23]},
			},
			{
				Name:    "apikey_group_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[22]},
			},
			{
				Name:    "apikey_status",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[6]},
			},
			{
				Name:    "apikey_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[3]},
			},
			{
				Name:    "apikey_last_used_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[7]},
			},
			{
				Name:    "apikey_quota_quota_used",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[10], APIKeysColumns[11]},
			},
			{
				Name:    "apikey_expires_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[12]},
			},
		},
	}
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "platform", Type: field.TypeString, Size: 50},
		{Name: "type", Type: field.TypeString, Size: 20},
		{Name: "credentials", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "extra", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "concurrency", Type: field.TypeInt, Default: 3},
		{Name: "load_factor", Type: field.TypeInt, Nullable: true},
		{Name: "priority", Type: field.TypeInt, Default: 50},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "error_message", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "auto_pause_on_expired", Type: field.TypeBool, Default: true},
		{Name: "schedulable", Type: field.TypeBool, Default: true},
		{Name: "rate_limited_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "rate_limit_reset_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "overload_until", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "temp_unschedulable_until", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "temp_unschedulable_reason", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "session_window_start", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "session_window_end", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "session_window_status", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "proxy_id", Type: field.TypeInt64, Nullable: true},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "accounts_proxies_proxy",
				Columns:    []*schema.Column{AccountsColumns[28]},
				RefColumns: []*schema.Column{ProxiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "account_platform",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[6]},
			},
			{
				Name:    "account_type",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[7]},
			},
			{
				Name:    "account_status",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[14]},
			},
			{
				Name:    "account_proxy_id",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[28]},
			},
			{
				Name:    "account_priority",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[12]},
			},
			{
				Name:    "account_last_used_at",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[16]},
			},
			{
				Name:    "account_schedulable",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[19]},
			},
			{
				Name:    "account_rate_limited_at",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[20]},
			},
			{
				Name:    "account_rate_limit_reset_at",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[21]},
			},
			{
				Name:    "account_overload_until",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[22]},
			},
			{
				Name:    "account_platform_priority",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[6], AccountsColumns[12]},
			},
			{
				Name:    "account_priority_status",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[12], AccountsColumns[14]},
			},
			{
				Name:    "account_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[3]},
			},
		},
	}
	// AccountGroupsColumns holds the columns for the "account_groups" table.
	AccountGroupsColumns = []*schema.Column{
		{Name: "priority", Type: field.TypeInt, Default: 50},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "account_id", Type: field.TypeInt64},
		{Name: "group_id", Type: field.TypeInt64},
	}
	// AccountGroupsTable holds the schema information for the "account_groups" table.
	AccountGroupsTable = &schema.Table{
		Name:       "account_groups",
		Columns:    AccountGroupsColumns,
		PrimaryKey: []*schema.Column{AccountGroupsColumns[2], AccountGroupsColumns[3]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "account_groups_accounts_account",
				Columns:    []*schema.Column{AccountGroupsColumns[2]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "account_groups_groups_group",
				Columns:    []*schema.Column{AccountGroupsColumns[3]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "accountgroup_group_id",
				Unique:  false,
				Columns: []*schema.Column{AccountGroupsColumns[3]},
			},
			{
				Name:    "accountgroup_priority",
				Unique:  false,
				Columns: []*schema.Column{AccountGroupsColumns[0]},
			},
		},
	}
	// AnnouncementsColumns holds the columns for the "announcements" table.
	AnnouncementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 200},
		{Name: "content", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "draft"},
		{Name: "notify_mode", Type: field.TypeString, Size: 20, Default: "silent"},
		{Name: "targeting", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "starts_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "ends_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// AnnouncementsTable holds the schema information for the "announcements" table.
	AnnouncementsTable = &schema.Table{
		Name:       "announcements",
		Columns:    AnnouncementsColumns,
		PrimaryKey: []*schema.Column{AnnouncementsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "announcement_status",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementsColumns[3]},
			},
			{
				Name:    "announcement_created_at",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementsColumns[10]},
			},
			{
				Name:    "announcement_starts_at",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementsColumns[6]},
			},
			{
				Name:    "announcement_ends_at",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementsColumns[7]},
			},
		},
	}
	// AnnouncementReadsColumns holds the columns for the "announcement_reads" table.
	AnnouncementReadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "read_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "announcement_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// AnnouncementReadsTable holds the schema information for the "announcement_reads" table.
	AnnouncementReadsTable = &schema.Table{
		Name:       "announcement_reads",
		Columns:    AnnouncementReadsColumns,
		PrimaryKey: []*schema.Column{AnnouncementReadsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "announcement_reads_announcements_reads",
				Columns:    []*schema.Column{AnnouncementReadsColumns[3]},
				RefColumns: []*schema.Column{AnnouncementsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "announcement_reads_users_announcement_reads",
				Columns:    []*schema.Column{AnnouncementReadsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "announcementread_announcement_id",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementReadsColumns[3]},
			},
			{
				Name:    "announcementread_user_id",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementReadsColumns[4]},
			},
			{
				Name:    "announcementread_read_at",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementReadsColumns[1]},
			},
			{
				Name:    "announcementread_announcement_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{AnnouncementReadsColumns[3], AnnouncementReadsColumns[4]},
			},
		},
	}
	// ErrorPassthroughRulesColumns holds the columns for the "error_passthrough_rules" table.
	ErrorPassthroughRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "error_codes", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "keywords", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "match_mode", Type: field.TypeString, Size: 10, Default: "any"},
		{Name: "platforms", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "passthrough_code", Type: field.TypeBool, Default: true},
		{Name: "response_code", Type: field.TypeInt, Nullable: true},
		{Name: "passthrough_body", Type: field.TypeBool, Default: true},
		{Name: "custom_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "skip_monitoring", Type: field.TypeBool, Default: false},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// ErrorPassthroughRulesTable holds the schema information for the "error_passthrough_rules" table.
	ErrorPassthroughRulesTable = &schema.Table{
		Name:       "error_passthrough_rules",
		Columns:    ErrorPassthroughRulesColumns,
		PrimaryKey: []*schema.Column{ErrorPassthroughRulesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "errorpassthroughrule_enabled",
				Unique:  false,
				Columns: []*schema.Column{ErrorPassthroughRulesColumns[4]},
			},
			{
				Name:    "errorpassthroughrule_priority",
				Unique:  false,
				Columns: []*schema.Column{ErrorPassthroughRulesColumns[5]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "is_exclusive", Type: field.TypeBool, Default: false},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "platform", Type: field.TypeString, Size: 50, Default: "anthropic"},
		{Name: "subscription_type", Type: field.TypeString, Size: 20, Default: "standard"},
		{Name: "daily_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "weekly_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "monthly_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "default_validity_days", Type: field.TypeInt, Default: 30},
		{Name: "image_price_1k", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "image_price_2k", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "image_price_4k", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "claude_code_only", Type: field.TypeBool, Default: false},
		{Name: "fallback_group_id", Type: field.TypeInt64, Nullable: true},
		{Name: "fallback_group_id_on_invalid_request", Type: field.TypeInt64, Nullable: true},
		{Name: "model_routing", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "model_routing_enabled", Type: field.TypeBool, Default: false},
		{Name: "mcp_xml_inject", Type: field.TypeBool, Default: true},
		{Name: "supported_model_scopes", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "allow_messages_dispatch", Type: field.TypeBool, Default: false},
		{Name: "require_oauth_only", Type: field.TypeBool, Default: false},
		{Name: "require_privacy_set", Type: field.TypeBool, Default: false},
		{Name: "default_mapped_model", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "messages_dispatch_model_config", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "group_status",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[8]},
			},
			{
				Name:    "group_platform",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[9]},
			},
			{
				Name:    "group_subscription_type",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[10]},
			},
			{
				Name:    "group_is_exclusive",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[7]},
			},
			{
				Name:    "group_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[3]},
			},
			{
				Name:    "group_sort_order",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[25]},
			},
		},
	}
	// IdempotencyRecordsColumns holds the columns for the "idempotency_records" table.
	IdempotencyRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "scope", Type: field.TypeString, Size: 128},
		{Name: "idempotency_key_hash", Type: field.TypeString, Size: 64},
		{Name: "request_fingerprint", Type: field.TypeString, Size: 64},
		{Name: "status", Type: field.TypeString, Size: 32},
		{Name: "response_status", Type: field.TypeInt, Nullable: true},
		{Name: "response_body", Type: field.TypeString, Nullable: true},
		{Name: "error_reason", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "locked_until", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// IdempotencyRecordsTable holds the schema information for the "idempotency_records" table.
	IdempotencyRecordsTable = &schema.Table{
		Name:       "idempotency_records",
		Columns:    IdempotencyRecordsColumns,
		PrimaryKey: []*schema.Column{IdempotencyRecordsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idempotencyrecord_scope_idempotency_key_hash",
				Unique:  true,
				Columns: []*schema.Column{IdempotencyRecordsColumns[3], IdempotencyRecordsColumns[4]},
			},
			{
				Name:    "idempotencyrecord_expires_at",
				Unique:  false,
				Columns: []*schema.Column{IdempotencyRecordsColumns[11]},
			},
			{
				Name:    "idempotencyrecord_status_locked_until",
				Unique:  false,
				Columns: []*schema.Column{IdempotencyRecordsColumns[6], IdempotencyRecordsColumns[10]},
			},
		},
	}
	// PaymentAuditLogsColumns holds the columns for the "payment_audit_logs" table.
	PaymentAuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "order_id", Type: field.TypeString, Size: 64},
		{Name: "action", Type: field.TypeString, Size: 50},
		{Name: "detail", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "operator", Type: field.TypeString, Size: 100, Default: "system"},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// PaymentAuditLogsTable holds the schema information for the "payment_audit_logs" table.
	PaymentAuditLogsTable = &schema.Table{
		Name:       "payment_audit_logs",
		Columns:    PaymentAuditLogsColumns,
		PrimaryKey: []*schema.Column{PaymentAuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "paymentauditlog_order_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentAuditLogsColumns[1]},
			},
		},
	}
	// PaymentOrdersColumns holds the columns for the "payment_orders" table.
	PaymentOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_email", Type: field.TypeString, Size: 255},
		{Name: "user_name", Type: field.TypeString, Size: 100},
		{Name: "user_notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "pay_amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "fee_rate", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "recharge_code", Type: field.TypeString, Size: 64},
		{Name: "out_trade_no", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "payment_type", Type: field.TypeString, Size: 30},
		{Name: "payment_trade_no", Type: field.TypeString, Size: 128},
		{Name: "pay_url", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "qr_code", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "qr_code_img", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "order_type", Type: field.TypeString, Size: 20, Default: "balance"},
		{Name: "plan_id", Type: field.TypeInt64, Nullable: true},
		{Name: "subscription_group_id", Type: field.TypeInt64, Nullable: true},
		{Name: "subscription_days", Type: field.TypeInt, Nullable: true},
		{Name: "provider_instance_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "status", Type: field.TypeString, Size: 30, Default: "PENDING"},
		{Name: "refund_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "refund_reason", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "refund_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "force_refund", Type: field.TypeBool, Default: false},
		{Name: "refund_requested_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "refund_request_reason", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "refund_requested_by", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "expires_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "paid_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "failed_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "failed_reason", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "client_ip", Type: field.TypeString, Size: 50},
		{Name: "src_host", Type: field.TypeString, Size: 255},
		{Name: "src_url", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// PaymentOrdersTable holds the schema information for the "payment_orders" table.
	PaymentOrdersTable = &schema.Table{
		Name:       "payment_orders",
		Columns:    PaymentOrdersColumns,
		PrimaryKey: []*schema.Column{PaymentOrdersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "payment_orders_users_payment_orders",
				Columns:    []*schema.Column{PaymentOrdersColumns[37]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "paymentorder_out_trade_no",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[8]},
			},
			{
				Name:    "paymentorder_user_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[37]},
			},
			{
				Name:    "paymentorder_status",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[19]},
			},
			{
				Name:    "paymentorder_expires_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[27]},
			},
			{
				Name:    "paymentorder_created_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[35]},
			},
			{
				Name:    "paymentorder_paid_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[28]},
			},
			{
				Name:    "paymentorder_payment_type_paid_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[9], PaymentOrdersColumns[28]},
			},
			{
				Name:    "paymentorder_order_type",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[14]},
			},
		},
	}
	// PaymentProviderInstancesColumns holds the columns for the "payment_provider_instances" table.
	PaymentProviderInstancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "provider_key", Type: field.TypeString, Size: 30},
		{Name: "name", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "config", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "supported_types", Type: field.TypeString, Size: 200, Default: ""},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "payment_mode", Type: field.TypeString, Size: 20, Default: ""},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "limits", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "refund_enabled", Type: field.TypeBool, Default: false},
		{Name: "allow_user_refund", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// PaymentProviderInstancesTable holds the schema information for the "payment_provider_instances" table.
	PaymentProviderInstancesTable = &schema.Table{
		Name:       "payment_provider_instances",
		Columns:    PaymentProviderInstancesColumns,
		PrimaryKey: []*schema.Column{PaymentProviderInstancesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "paymentproviderinstance_provider_key",
				Unique:  false,
				Columns: []*schema.Column{PaymentProviderInstancesColumns[1]},
			},
			{
				Name:    "paymentproviderinstance_enabled",
				Unique:  false,
				Columns: []*schema.Column{PaymentProviderInstancesColumns[5]},
			},
		},
	}
	// PromoCodesColumns holds the columns for the "promo_codes" table.
	PromoCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "bonus_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "max_uses", Type: field.TypeInt, Default: 0},
		{Name: "used_count", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// PromoCodesTable holds the schema information for the "promo_codes" table.
	PromoCodesTable = &schema.Table{
		Name:       "promo_codes",
		Columns:    PromoCodesColumns,
		PrimaryKey: []*schema.Column{PromoCodesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "promocode_status",
				Unique:  false,
				Columns: []*schema.Column{PromoCodesColumns[5]},
			},
			{
				Name:    "promocode_expires_at",
				Unique:  false,
				Columns: []*schema.Column{PromoCodesColumns[6]},
			},
		},
	}
	// PromoCodeUsagesColumns holds the columns for the "promo_code_usages" table.
	PromoCodeUsagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "bonus_amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "used_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "promo_code_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// PromoCodeUsagesTable holds the schema information for the "promo_code_usages" table.
	PromoCodeUsagesTable = &schema.Table{
		Name:       "promo_code_usages",
		Columns:    PromoCodeUsagesColumns,
		PrimaryKey: []*schema.Column{PromoCodeUsagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "promo_code_usages_promo_codes_usage_records",
				Columns:    []*schema.Column{PromoCodeUsagesColumns[3]},
				RefColumns: []*schema.Column{PromoCodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "promo_code_usages_users_promo_code_usages",
				Columns:    []*schema.Column{PromoCodeUsagesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "promocodeusage_promo_code_id",
				Unique:  false,
				Columns: []*schema.Column{PromoCodeUsagesColumns[3]},
			},
			{
				Name:    "promocodeusage_user_id",
				Unique:  false,
				Columns: []*schema.Column{PromoCodeUsagesColumns[4]},
			},
			{
				Name:    "promocodeusage_promo_code_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{PromoCodeUsagesColumns[3], PromoCodeUsagesColumns[4]},
			},
		},
	}
	// ProxiesColumns holds the columns for the "proxies" table.
	ProxiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "protocol", Type: field.TypeString, Size: 20},
		{Name: "host", Type: field.TypeString, Size: 255},
		{Name: "port", Type: field.TypeInt},
		{Name: "username", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "password", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
	}
	// ProxiesTable holds the schema information for the "proxies" table.
	ProxiesTable = &schema.Table{
		Name:       "proxies",
		Columns:    ProxiesColumns,
		PrimaryKey: []*schema.Column{ProxiesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "proxy_status",
				Unique:  false,
				Columns: []*schema.Column{ProxiesColumns[10]},
			},
			{
				Name:    "proxy_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{ProxiesColumns[3]},
			},
		},
	}
	// RedeemCodesColumns holds the columns for the "redeem_codes" table.
	RedeemCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "type", Type: field.TypeString, Size: 20, Default: "balance"},
		{Name: "value", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "unused"},
		{Name: "used_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "validity_days", Type: field.TypeInt, Default: 30},
		{Name: "group_id", Type: field.TypeInt64, Nullable: true},
		{Name: "used_by", Type: field.TypeInt64, Nullable: true},
	}
	// RedeemCodesTable holds the schema information for the "redeem_codes" table.
	RedeemCodesTable = &schema.Table{
		Name:       "redeem_codes",
		Columns:    RedeemCodesColumns,
		PrimaryKey: []*schema.Column{RedeemCodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "redeem_codes_groups_redeem_codes",
				Columns:    []*schema.Column{RedeemCodesColumns[9]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "redeem_codes_users_redeem_codes",
				Columns:    []*schema.Column{RedeemCodesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "redeemcode_status",
				Unique:  false,
				Columns: []*schema.Column{RedeemCodesColumns[4]},
			},
			{
				Name:    "redeemcode_used_by",
				Unique:  false,
				Columns: []*schema.Column{RedeemCodesColumns[10]},
			},
			{
				Name:    "redeemcode_group_id",
				Unique:  false,
				Columns: []*schema.Column{RedeemCodesColumns[9]},
			},
		},
	}
	// SecuritySecretsColumns holds the columns for the "security_secrets" table.
	SecuritySecretsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "key", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "value", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
	}
	// SecuritySecretsTable holds the schema information for the "security_secrets" table.
	SecuritySecretsTable = &schema.Table{
		Name:       "security_secrets",
		Columns:    SecuritySecretsColumns,
		PrimaryKey: []*schema.Column{SecuritySecretsColumns[0]},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "value", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// SubscriptionPlansColumns holds the columns for the "subscription_plans" table.
	SubscriptionPlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "group_id", Type: field.TypeInt64},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "price", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "original_price", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "validity_days", Type: field.TypeInt, Default: 30},
		{Name: "validity_unit", Type: field.TypeString, Size: 10, Default: "day"},
		{Name: "features", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "product_name", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "for_sale", Type: field.TypeBool, Default: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// SubscriptionPlansTable holds the schema information for the "subscription_plans" table.
	SubscriptionPlansTable = &schema.Table{
		Name:       "subscription_plans",
		Columns:    SubscriptionPlansColumns,
		PrimaryKey: []*schema.Column{SubscriptionPlansColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "subscriptionplan_group_id",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionPlansColumns[1]},
			},
			{
				Name:    "subscriptionplan_for_sale",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionPlansColumns[10]},
			},
		},
	}
	// TLSFingerprintProfilesColumns holds the columns for the "tls_fingerprint_profiles" table.
	TLSFingerprintProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "enable_grease", Type: field.TypeBool, Default: false},
		{Name: "cipher_suites", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "curves", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "point_formats", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "signature_algorithms", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "alpn_protocols", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "supported_versions", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "key_share_groups", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "psk_modes", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "extensions", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
	}
	// TLSFingerprintProfilesTable holds the schema information for the "tls_fingerprint_profiles" table.
	TLSFingerprintProfilesTable = &schema.Table{
		Name:       "tls_fingerprint_profiles",
		Columns:    TLSFingerprintProfilesColumns,
		PrimaryKey: []*schema.Column{TLSFingerprintProfilesColumns[0]},
	}
	// UsageCleanupTasksColumns holds the columns for the "usage_cleanup_tasks" table.
	UsageCleanupTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "status", Type: field.TypeString, Size: 20},
		{Name: "filters", Type: field.TypeJSON},
		{Name: "created_by", Type: field.TypeInt64},
		{Name: "deleted_rows", Type: field.TypeInt64, Default: 0},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "canceled_by", Type: field.TypeInt64, Nullable: true},
		{Name: "canceled_at", Type: field.TypeTime, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
	}
	// UsageCleanupTasksTable holds the schema information for the "usage_cleanup_tasks" table.
	UsageCleanupTasksTable = &schema.Table{
		Name:       "usage_cleanup_tasks",
		Columns:    UsageCleanupTasksColumns,
		PrimaryKey: []*schema.Column{UsageCleanupTasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "usagecleanuptask_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageCleanupTasksColumns[3], UsageCleanupTasksColumns[1]},
			},
			{
				Name:    "usagecleanuptask_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageCleanupTasksColumns[1]},
			},
			{
				Name:    "usagecleanuptask_canceled_at",
				Unique:  false,
				Columns: []*schema.Column{UsageCleanupTasksColumns[9]},
			},
		},
	}
	// UsageLogsColumns holds the columns for the "usage_logs" table.
	UsageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "request_id", Type: field.TypeString, Size: 64},
		{Name: "model", Type: field.TypeString, Size: 100},
		{Name: "requested_model", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "upstream_model", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "channel_id", Type: field.TypeInt64, Nullable: true},
		{Name: "model_mapping_chain", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "billing_tier", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "billing_mode", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "output_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_creation_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_read_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_creation_5m_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_creation_1h_tokens", Type: field.TypeInt, Default: 0},
		{Name: "input_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "output_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "cache_creation_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "cache_read_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "total_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "actual_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "account_rate_multiplier", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "billing_type", Type: field.TypeInt8, Default: 0},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "duration_ms", Type: field.TypeInt, Nullable: true},
		{Name: "first_token_ms", Type: field.TypeInt, Nullable: true},
		{Name: "user_agent", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "ip_address", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "image_count", Type: field.TypeInt, Default: 0},
		{Name: "image_size", Type: field.TypeString, Nullable: true, Size: 10},
		{Name: "cache_ttl_overridden", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "api_key_id", Type: field.TypeInt64},
		{Name: "account_id", Type: field.TypeInt64},
		{Name: "group_id", Type: field.TypeInt64, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "subscription_id", Type: field.TypeInt64, Nullable: true},
	}
	// UsageLogsTable holds the schema information for the "usage_logs" table.
	UsageLogsTable = &schema.Table{
		Name:       "usage_logs",
		Columns:    UsageLogsColumns,
		PrimaryKey: []*schema.Column{UsageLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "usage_logs_api_keys_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[33]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "usage_logs_accounts_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[34]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "usage_logs_groups_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[35]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_users_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[36]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "usage_logs_user_subscriptions_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[37]},
				RefColumns: []*schema.Column{UserSubscriptionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usagelog_user_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[36]},
			},
			{
				Name:    "usagelog_api_key_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[33]},
			},
			{
				Name:    "usagelog_account_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[34]},
			},
			{
				Name:    "usagelog_group_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[35]},
			},
			{
				Name:    "usagelog_subscription_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[37]},
			},
			{
				Name:    "usagelog_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[32]},
			},
			{
				Name:    "usagelog_model",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[2]},
			},
			{
				Name:    "usagelog_requested_model",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[3]},
			},
			{
				Name:    "usagelog_request_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[1]},
			},
			{
				Name:    "usagelog_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[36], UsageLogsColumns[32]},
			},
			{
				Name:    "usagelog_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[33], UsageLogsColumns[32]},
			},
			{
				Name:    "usagelog_group_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[35], UsageLogsColumns[32]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "password_hash", Type: field.TypeString, Size: 255},
		{Name: "role", Type: field.TypeString, Size: 20, Default: "user"},
		{Name: "balance", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "concurrency", Type: field.TypeInt, Default: 5},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "username", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "notes", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "totp_secret_encrypted", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "totp_enabled", Type: field.TypeBool, Default: false},
		{Name: "totp_enabled_at", Type: field.TypeTime, Nullable: true},
		{Name: "balance_notify_enabled", Type: field.TypeBool, Default: true},
		{Name: "balance_notify_threshold_type", Type: field.TypeString, Default: "fixed"},
		{Name: "balance_notify_threshold", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "balance_notify_extra_emails", Type: field.TypeString, Default: "[]", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "total_recharged", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[9]},
			},
			{
				Name:    "user_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[3]},
			},
		},
	}
	// UserAllowedGroupsColumns holds the columns for the "user_allowed_groups" table.
	UserAllowedGroupsColumns = []*schema.Column{
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "group_id", Type: field.TypeInt64},
	}
	// UserAllowedGroupsTable holds the schema information for the "user_allowed_groups" table.
	UserAllowedGroupsTable = &schema.Table{
		Name:       "user_allowed_groups",
		Columns:    UserAllowedGroupsColumns,
		PrimaryKey: []*schema.Column{UserAllowedGroupsColumns[1], UserAllowedGroupsColumns[2]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_allowed_groups_users_user",
				Columns:    []*schema.Column{UserAllowedGroupsColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_allowed_groups_groups_group",
				Columns:    []*schema.Column{UserAllowedGroupsColumns[2]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userallowedgroup_group_id",
				Unique:  false,
				Columns: []*schema.Column{UserAllowedGroupsColumns[2]},
			},
		},
	}
	// UserAttributeDefinitionsColumns holds the columns for the "user_attribute_definitions" table.
	UserAttributeDefinitionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "key", Type: field.TypeString, Size: 100},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "type", Type: field.TypeString, Size: 20},
		{Name: "options", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "required", Type: field.TypeBool, Default: false},
		{Name: "validation", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "placeholder", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
		{Name: "enabled", Type: field.TypeBool, Default: true},
	}
	// UserAttributeDefinitionsTable holds the schema information for the "user_attribute_definitions" table.
	UserAttributeDefinitionsTable = &schema.Table{
		Name:       "user_attribute_definitions",
		Columns:    UserAttributeDefinitionsColumns,
		PrimaryKey: []*schema.Column{UserAttributeDefinitionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "userattributedefinition_key",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeDefinitionsColumns[4]},
			},
			{
				Name:    "userattributedefinition_enabled",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeDefinitionsColumns[13]},
			},
			{
				Name:    "userattributedefinition_display_order",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeDefinitionsColumns[12]},
			},
			{
				Name:    "userattributedefinition_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeDefinitionsColumns[3]},
			},
		},
	}
	// UserAttributeValuesColumns holds the columns for the "user_attribute_values" table.
	UserAttributeValuesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "value", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "attribute_id", Type: field.TypeInt64},
	}
	// UserAttributeValuesTable holds the schema information for the "user_attribute_values" table.
	UserAttributeValuesTable = &schema.Table{
		Name:       "user_attribute_values",
		Columns:    UserAttributeValuesColumns,
		PrimaryKey: []*schema.Column{UserAttributeValuesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_attribute_values_users_attribute_values",
				Columns:    []*schema.Column{UserAttributeValuesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_attribute_values_user_attribute_definitions_values",
				Columns:    []*schema.Column{UserAttributeValuesColumns[5]},
				RefColumns: []*schema.Column{UserAttributeDefinitionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userattributevalue_user_id_attribute_id",
				Unique:  true,
				Columns: []*schema.Column{UserAttributeValuesColumns[4], UserAttributeValuesColumns[5]},
			},
			{
				Name:    "userattributevalue_attribute_id",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeValuesColumns[5]},
			},
		},
	}
	// UserSubscriptionsColumns holds the columns for the "user_subscriptions" table.
	UserSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "starts_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "expires_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "daily_window_start", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "weekly_window_start", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "monthly_window_start", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "daily_usage_usd", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "weekly_usage_usd", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "monthly_usage_usd", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "assigned_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "group_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "assigned_by", Type: field.TypeInt64, Nullable: true},
	}
	// UserSubscriptionsTable holds the schema information for the "user_subscriptions" table.
	UserSubscriptionsTable = &schema.Table{
		Name:       "user_subscriptions",
		Columns:    UserSubscriptionsColumns,
		PrimaryKey: []*schema.Column{UserSubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_subscriptions_groups_subscriptions",
				Columns:    []*schema.Column{UserSubscriptionsColumns[15]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_subscriptions_users_subscriptions",
				Columns:    []*schema.Column{UserSubscriptionsColumns[16]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_subscriptions_users_assigned_subscriptions",
				Columns:    []*schema.Column{UserSubscriptionsColumns[17]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usersubscription_user_id",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[16]},
			},
			{
				Name:    "usersubscription_group_id",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[15]},
			},
			{
				Name:    "usersubscription_status",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[6]},
			},
			{
				Name:    "usersubscription_expires_at",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[5]},
			},
			{
				Name:    "usersubscription_user_id_status_expires_at",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[16], UserSubscriptionsColumns[6], UserSubscriptionsColumns[5]},
			},
			{
				Name:    "usersubscription_assigned_by",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[17]},
			},
			{
				Name:    "usersubscription_user_id_group_id",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[16], UserSubscriptionsColumns[15]},
			},
			{
				Name:    "usersubscription_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		AccountsTable,
		AccountGroupsTable,
		AnnouncementsTable,
		AnnouncementReadsTable,
		ErrorPassthroughRulesTable,
		GroupsTable,
		IdempotencyRecordsTable,
		PaymentAuditLogsTable,
		PaymentOrdersTable,
		PaymentProviderInstancesTable,
		PromoCodesTable,
		PromoCodeUsagesTable,
		ProxiesTable,
		RedeemCodesTable,
		SecuritySecretsTable,
		SettingsTable,
		SubscriptionPlansTable,
		TLSFingerprintProfilesTable,
		UsageCleanupTasksTable,
		UsageLogsTable,
		UsersTable,
		UserAllowedGroupsTable,
		UserAttributeDefinitionsTable,
		UserAttributeValuesTable,
		UserSubscriptionsTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = GroupsTable
	APIKeysTable.ForeignKeys[1].RefTable = UsersTable
	APIKeysTable.Annotation = &entsql.Annotation{
		Table: "api_keys",
	}
	AccountsTable.ForeignKeys[0].RefTable = ProxiesTable
	AccountsTable.Annotation = &entsql.Annotation{
		Table: "accounts",
	}
	AccountGroupsTable.ForeignKeys[0].RefTable = AccountsTable
	AccountGroupsTable.ForeignKeys[1].RefTable = GroupsTable
	AccountGroupsTable.Annotation = &entsql.Annotation{
		Table: "account_groups",
	}
	AnnouncementsTable.Annotation = &entsql.Annotation{
		Table: "announcements",
	}
	AnnouncementReadsTable.ForeignKeys[0].RefTable = AnnouncementsTable
	AnnouncementReadsTable.ForeignKeys[1].RefTable = UsersTable
	AnnouncementReadsTable.Annotation = &entsql.Annotation{
		Table: "announcement_reads",
	}
	ErrorPassthroughRulesTable.Annotation = &entsql.Annotation{
		Table: "error_passthrough_rules",
	}
	GroupsTable.Annotation = &entsql.Annotation{
		Table: "groups",
	}
	IdempotencyRecordsTable.Annotation = &entsql.Annotation{
		Table: "idempotency_records",
	}
	PaymentAuditLogsTable.Annotation = &entsql.Annotation{
		Table: "payment_audit_logs",
	}
	PaymentOrdersTable.ForeignKeys[0].RefTable = UsersTable
	PaymentOrdersTable.Annotation = &entsql.Annotation{
		Table: "payment_orders",
	}
	PaymentProviderInstancesTable.Annotation = &entsql.Annotation{
		Table: "payment_provider_instances",
	}
	PromoCodesTable.Annotation = &entsql.Annotation{
		Table: "promo_codes",
	}
	PromoCodeUsagesTable.ForeignKeys[0].RefTable = PromoCodesTable
	PromoCodeUsagesTable.ForeignKeys[1].RefTable = UsersTable
	PromoCodeUsagesTable.Annotation = &entsql.Annotation{
		Table: "promo_code_usages",
	}
	ProxiesTable.Annotation = &entsql.Annotation{
		Table: "proxies",
	}
	RedeemCodesTable.ForeignKeys[0].RefTable = GroupsTable
	RedeemCodesTable.ForeignKeys[1].RefTable = UsersTable
	RedeemCodesTable.Annotation = &entsql.Annotation{
		Table: "redeem_codes",
	}
	SecuritySecretsTable.Annotation = &entsql.Annotation{
		Table: "security_secrets",
	}
	SettingsTable.Annotation = &entsql.Annotation{
		Table: "settings",
	}
	SubscriptionPlansTable.Annotation = &entsql.Annotation{
		Table: "subscription_plans",
	}
	TLSFingerprintProfilesTable.Annotation = &entsql.Annotation{
		Table: "tls_fingerprint_profiles",
	}
	UsageCleanupTasksTable.Annotation = &entsql.Annotation{
		Table: "usage_cleanup_tasks",
	}
	UsageLogsTable.ForeignKeys[0].RefTable = APIKeysTable
	UsageLogsTable.ForeignKeys[1].RefTable = AccountsTable
	UsageLogsTable.ForeignKeys[2].RefTable = GroupsTable
	UsageLogsTable.ForeignKeys[3].RefTable = UsersTable
	UsageLogsTable.ForeignKeys[4].RefTable = UserSubscriptionsTable
	UsageLogsTable.Annotation = &entsql.Annotation{
		Table: "usage_logs",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
	UserAllowedGroupsTable.ForeignKeys[0].RefTable = UsersTable
	UserAllowedGroupsTable.ForeignKeys[1].RefTable = GroupsTable
	UserAllowedGroupsTable.Annotation = &entsql.Annotation{
		Table: "user_allowed_groups",
	}
	UserAttributeDefinitionsTable.Annotation = &entsql.Annotation{
		Table: "user_attribute_definitions",
	}
	UserAttributeValuesTable.ForeignKeys[0].RefTable = UsersTable
	UserAttributeValuesTable.ForeignKeys[1].RefTable = UserAttributeDefinitionsTable
	UserAttributeValuesTable.Annotation = &entsql.Annotation{
		Table: "user_attribute_values",
	}
	UserSubscriptionsTable.ForeignKeys[0].RefTable = GroupsTable
	UserSubscriptionsTable.ForeignKeys[1].RefTable = UsersTable
	UserSubscriptionsTable.ForeignKeys[2].RefTable = UsersTable
	UserSubscriptionsTable.Annotation = &entsql.Annotation{
		Table: "user_subscriptions",
	}
}
